### ISSUE TITLE
#include "../common/cpu_bitmap.h"无法引入

### ISSUE THREAD

**Issue by MastXu** [Yannnnnnnnnnnn/cuda_by_example#2]
你好。请教一下，#include "../common/cpu_bitmap.h" 无法引入，是配置的问题么？

我安装的是 CUDA 9.2 ，在 sample文件夹中找不到 cpu_bitmap.h 以及 book.h 头文件；

**Comment by yanqswhu** [comment]
请问是那一个程序报错了？可以提供更详细的信息吗？
我上传的版本里把之前的一些文件删掉了

**Comment by MastXu** [comment]
嗯嗯。忽视我的提问吧。
是我包路径出了问题。
